### ISSUE TITLE
RFE: send mail on failed backups

### ISSUE THREAD

**Issue by svfrd** [ewxrjk/rsbackup#103]
hello,
in the past it happened again and again that backups were not carried out because there was an error. For example, "rsync" was not found on the remote side or the SSH host key has changed.

For these cases I would like to get a mail with a warning.
Is this possible with the current release?

In the worst case several weeks have passed before the error is noticed in the monthly report.

**Comment by ewxrjk** [comment]
How are you running it? I run it from cron (and the Debian package is set up to do that automatically), which means that errors are reported by email automatically, for example:

```
From: root@(mydomain) (Cron Daemon)
To: root@(mydomain)
Date: Sat, 03 Dec 2022 06:19:07 +0000

/etc/cron.hourly/rsbackup:
WARNING: backup of embelyon:root to backup13: rsync: exited with status 12
Failed to find executable rsync: No such file or directory
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [Receiver=3.2.3]
```
