### ISSUE TITLE
Removing really slow

### ISSUE THREAD

**Issue by kugel-** [ewxrjk/rsbackup#107]
I'm using rsbackup to backup my home directory to a local xfs drive. I found that the backup time became unbearable (larger than 24h) because pruning old backups is slow.

For example, deleting an old backups started yesterday at 11:14 and is still running. A quick `ls` on the backup storage suggests there's still lots of directories to be deleted.

Part of the reason seems to be that XFS is not good at deleting tons of hardlinks. But there are also some sources on the Internet, e.g. https://www.slashroot.in/which-is-the-fastest-method-to-delete-files-in-linux, that suggest that `rm -rf` is particularly slow.

Since rsbackup already depends on rsync, would it make sense to use rsync to do the deletion as the above block suggests? Just needs an empty source directory to sync from.

**Comment by ewxrjk** [comment]
The linked page doesn't test `rm -rf` as far as I can see, it tests `rm -f *` (which fails because the argument list is too long). Do you have a reference which compares `rm -rf` to other approaches?
