### ISSUE TITLE
Backup size calculations and locales

### ISSUE THREAD

**Issue by ewxrjk** [ewxrjk/rsbackup#111]
# Expected Behaviour

Backup report shows backup sizes.

# Actual Behavior

Backup size column is blank.

# Investigation

A user reported that the backup size column in the report wasn't working. The rsync output makes clear why:

```
Number of files: 5.501 (reg: 1.613, dir: 298, link: 3.590)
Number of created files: 1 (reg: 1)
Number of deleted files: 0
Number of regular files transferred: 1
Total file size: 2.793.565.636 bytes
Total transferred file size: 123.679.604 bytes
Literal data: 4.481.180 bytes
Matched data: 119.198.424 bytes
File list size: 46.919
File list generation time: 0,001 seconds
File list transfer time: 0,000 seconds
Total bytes sent: 78.358
Total bytes received: 4.593.544

sent 78.358 bytes  received 4.593.544 bytes  444.943,05 bytes/sec
total size is 2.793.565.636  speedup is 597,95
```

The regexp (see https://github.com/ewxrjk/rsbackup/blob/master/src/Backup.cc#L89) currently only expects digits and commas, so it fails to extract the backup size from the rsync output.

# Workaround

Override the locale (e.g. `LANG=en_GB.UTF-8` or something like that) when running rsbackup.

# Discussion

* rsbackup could have a wide regexp for parsing rsync output
* rsbackup could set the locale (to what?) when running rsync

**Comment by ijackson** [comment]
(I saw this go by on sgo-software-discuss)

I think if you're parsing the output you want `LC_MESSAGES=C.utf-8` at least.  Maybe override the whole `LANG `to `C.utf-8`?  Although not sure if that's available everywhere...

Also you might want to file a "look what you made me do (with your lack of a json report)" ticket against rsync.

**Comment by ewxrjk** [comment]
* This is new behavior introduced in https://github.com/WayneD/rsync/commit/80c64dc3b3e82c84ea52528722ee2db1567ab4c1 (3.2.4)
* There's some [odd stuff to figure out the thousands separator](https://github.com/WayneD/rsync/blob/master/lib/compat.c#L25) rather than just using `%'d` etc
  * I think this code will go wrong in  some locales (e.g. French locales which, empirically, want a space)
* The new behaviour is acknowledged in [rsync's NEWS.md](https://github.com/WayneD/rsync/blob/master/NEWS.md#news-for-rsync-324-15-apr-2022) but the recommendation assumes that a predictable UTF-8 locale is available, which I'm not sure is sufficiently widely true to build a choice into rsbackup
* The `--no-human-readable` (present since 2007 or so) option completely suppresses the use of thousands separators, correct or otherwise, so that's what I'll do for now.
