### ISSUE TITLE
We end up running pre-access-hook and not doing any backups a lot

### ISSUE THREAD

**Issue by senji-rsbackup** [ewxrjk/rsbackup#16]
I have a few hosts that are on an 'hourly' backup rotation because they're intermittently turned on/online.  I also always have disks that are offsite and use pre-access-hook to opportunistically mount backup devices.  

This appears to be a triangle of badness which results in rsbackup being invoked every hour; mounting all its devices; and then deciding it's not going to back anything up.

I think this can only be solved by adding an additional hook to determine which devices are available and then having an execution flow that looks something like:
1. Determine which devices are available
2. Iterate through volumes until we find one that needs backing up and is available
3. Run pre-access-hook for any devices we can back that volume up to
4. Back up that volume
5. Continue iterating.  If we find any volumes that need backing up onto devices we've not mounted yet we might need to run pre-access-hook for those devices too (should pre-access-hook be idempotent?)
6. Run post-access-hook on any devices we've mounted

**Comment by ewxrjk** [comment]
Does this (still) happen in 2.1 (or HEAD)? Unless I'm missing something, pre-access hooks are only invoked when at least one of the following is true:
1. There is actually something to back up.
2. There is something to prune.
3. During volume retire.

**Comment by ewxrjk** [comment]
After more than a year with no response I assume this isn't a problem any more.
