### ISSUE TITLE
Concurrent backups of remote hosts

### ISSUE THREAD

**Issue by senji-rsbackup** [ewxrjk/rsbackup#18]
When backing up remote hosts it seems that rsbackup is rarely if ever I/O bound on the target device; would it be possible to have a configuration option to run backups on multiple hosts at once?

**Comment by ewxrjk** [comment]
I've added issue #24 to request concurrent pruning. I'll probably attempt that before concurrent backup, as it's likely to be easier.

**Comment by ewxrjk** [comment]
https://github.com/ewxrjk/rsbackup/wiki/Concurrency is the design. It's been implemented for pruning but not for backups, which will be a substantial upheaval.

**Comment by ewxrjk** [comment]
`master` now supports concurrent backups of distinct hosts to distinct devices - in other words, no concurrent use of any single resource.

Concurrent use of devices and/or hosts could potentially be added, if that's desirable. The former might produce poor locality of reference on backup devices?

**Comment by ewxrjk** [comment]
I'm going to reject idea of concurrency 'within' devices and have created #58 for concurrency with hosts, meaning that this issue is now closed.
