### ISSUE TITLE
report emails should include count of minor/major errors in Subject line

### ISSUE THREAD

**Issue by pm215** [ewxrjk/rsbackup#22]
I typically only scan the subjects of my system email, so it would be useful if rsbackup's report mails could have an indication in their subject lines of whether there are issues within that need urgent investigation or not.

Suggested implementation: categorize everything in the report by severity (major/minor/info, error/warning/info or similar), and then have the subject be "Backup report ($DATE) [errors: 1 major, 2 minor]" (or perhaps "[1 error, 2 warnings]").

Example major errors:
 * always-up machine not present
 * device and host both present but rsync failed
 * host has not been backed up in $LIMIT days [configurable]

Example minor errors/warnings:
 * Unknown volume $VOL on host $H

Example info:
 * Log pruning
 * Host H skipped because not present

**Comment by ewxrjk** [comment]
Have a look at the issue22 branch: https://github.com/ewxrjk/rsbackup/tree/issue22

It's not quite the same as you ask for but it does include details of various error/warning conditions in the subject line.

`always-up` machines not being present is the trickiest to implement. There isn't really a sensible way to record that this was true on the last attempt to make a backup and checking each time the report is generated would be slow. The only thing I can think of is faking up a failed `Backup` object for at least one (volume, device) pair for that host.

However setting a low max-age for such machines should make the same condition visible in the subject line.

**Comment by ewxrjk** [comment]
I think this is in its final (or at least, releasable) form now.
