### ISSUE TITLE
/snap clashes with new 'snap' packaging format

### ISSUE THREAD

**Issue by jtn20** [ewxrjk/rsbackup#28]
rsbackup-snapshot-hook's default location for LVM snapshots, /snap, has been appropriated by Ubuntu 16.04 (at least) for this thing: http://snapcraft.io/

This might affect other distros too: http://snapcraft.io/docs/core/install

(I noticed because Ubuntu 14.04, which doesn't have this stuff, nevertheless got an update to 'sudo' with changelog entry "debian/sudoers: include /snap/bin in the secure_path (LP: #1595558)". I suppose this could possibly have unfortunate consequences.)

**Comment by ewxrjk** [comment]
Suggestions for a location less at risk of being landgrabbed would be welcome.
