### ISSUE TITLE
Back up xattrs?

### ISSUE THREAD

**Issue by cjwatson** [ewxrjk/rsbackup#37]
After restoring my laptop's root filesystem from backup, I noticed that (e.g.) `mtr` didn't work because it didn't have the required capabilities.  I had to grep for `setcap` in `/var/lib/dpkg/info/*.postinst` and reapply all the capabilities there, and of course that leaves me unsure whether I missed anything.

Could rsbackup perhaps start backing up xattrs, using `rsync --xattrs`, and maybe also `--acls`?  That would imply also adjusting the restore instructions in rsbackup(1).

**Comment by ewxrjk** [comment]
Yes, I think it's just a bug that it doesn't do so.

**Comment by ewxrjk** [comment]
I'm reopening this issue out of dissatisfaction with the approach taken on macOS. At present macOS users silently lose ACLs from their files, and if they install an `rsync` from this decade it won't work.

My preferred strategy is a config option (or options) allowing fine-grained control over the `rsync` options used (with the usual global/host/volume inheritance logic). The defaults would reflect a fully accurate backup with a modern `rsync`, with an explicit manual page and tutorial section on what to do on macOS.
