### ISSUE TITLE
rsbackup --retire host doesn't warn that it's going to delete all the backups for that host

### ISSUE THREAD

**Issue by pm215** [ewxrjk/rsbackup#38]
I was expecting 'rsbackup --retire host' to mean "forget about this host", but it means (as documented in the manual) "forget about this post and also delete all the backups". I think it would be nice if rsbackup had a confirmation prompt to check that you really wanted to blow away your backups before it fires up the rm -rf...

**Comment by ewxrjk** [comment]
Yes, I think that's sufficient of a booby-trap to be worth a behavior change.

**Comment by ewxrjk** [comment]
fixed in e2a2659edc3c0be171c1cc5f27990b0f5ba0a06d
