### ISSUE TITLE
rsbackup --retire host doesn't have any progress indication while it does long-running rm

### ISSUE THREAD

**Issue by pm215** [ewxrjk/rsbackup#39]
rsbackup --retire host runs an 'rm -rf' to delete all the backups for the host, which can take a long while, but it doesn't print any indication that this is what's happening or progress indication, which makes it look like the program has just hung, which I always find alarming in backup software :-)

**Comment by ewxrjk** [comment]
Is `--verbose` good enough for this?

**Comment by pm215** [comment]
I guess in combination with the proposed "do you really want to delete the backups" prompt it would be -- if the program sits doing nothing after you've said 'yes' to the prompt it's not too unobvious that it might be because it's doing the deletion.
