### ISSUE TITLE
Feature request:  option to backup volumes without compression 

### ISSUE THREAD

**Issue by d1mertz1** [ewxrjk/rsbackup#41]
I'd like to use rsbackup to backup a volume containing already compressed data (fotos and videos).
In that use case it does not make sense to use the "--compress" rsync option. Unfortunately it seems that this option is hardcoded and cannot be overriden easily.

It would be really usefull to have an option on volume level to suppress the "--compress" passed to rsync.

Thanks,
Denis

**Comment by ewxrjk** [comment]
This should be possible in the the next release, using the options added in https://github.com/ewxrjk/rsbackup/commit/4a4b17424ab3c85c0fdf3cbdbbf807b4de50630a.

**Comment by d1mertz1** [comment]
great :-)

i managed to build this from source (master) and i just tried  it out.
It works on host level, but it does not on volume level.
But according to rsbackup(5) the new option rsync-base-options should be inheritable, so it should work on volume level as well ?

Anyway on host level this is already a big help

**Comment by ewxrjk** [comment]
Pull and try again l-)

**Comment by d1mertz1** [comment]
It works as expected now.

The issue can be closed.

Thanks !
