### ISSUE TITLE
could rsbackup have a mollyguard check that device-id is actually at the root of a filesystem?

### ISSUE THREAD

**Issue by pm215** [ewxrjk/rsbackup#42]
Hi; this is a wishlist suggestion based on a user error I made this week bringing a new backup disk into service. Basically when I created the "device-id" file I forgot to actually mount the backup disk first. The result was that rsbackup happily started to back the machine's root disk up to a subdirectory of itself, until it ran out of disk space.

Would it be possible/sensible for rsbackup to complain if the directory with device-id isn't actually a filesystem root? (I guess you'd want an override for people doing odd things, but the 99% usecase is presumably that it should be the fs root.)

**Comment by ewxrjk** [comment]
Yes, I think this is a good idea.
