### ISSUE TITLE
error compilation on CentOS 7.6.1810

### ISSUE THREAD

**Issue by rahu-tree** [ewxrjk/rsbackup#64]
CXX      Conf.o
In file included from Conf.cc:25:0:
/usr/include/boost/smart_ptr/detail/shared_count.hpp: In constructor ‘boost::detail::shared_count::shared_count(P, boost::detail::sp_inplace_tag<D>)’:
Utils.h:356:68: error: expected primary-expression before ‘)’ token
   (void)(globalDebug && write_debug(__FILE__, __LINE__, __VA_ARGS__))
                                                                    ^
/usr/include/boost/smart_ptr/detail/shared_count.hpp: In constructor ‘boost::detail::shared_count::shared_count(P, boost::detail::sp_inplace_tag<D>, A)’:
Utils.h:356:68: error: expected primary-expression before ‘)’ token
   (void)(globalDebug && write_debug(__FILE__, __LINE__, __VA_ARGS__))
                                                                    ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-cast-function-type" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-c++14-extensions" [-Werror]
cc1plus: all warnings being treated as errors
make[1]: *** [Conf.o] Error 1

**Comment by ewxrjk** [comment]
Thankyou for the bug report.
Please see if this branch works for you: https://github.com/ewxrjk/rsbackup/tree/issue64
