### ISSUE TITLE
make check fail on CentOS 7.9.2009

### ISSUE THREAD

**Issue by rahu-tree** [ewxrjk/rsbackup#84]
Hi

After compile I run 'make check' and this was fail:

# make check
Making check in src
make[1]: Entering directory `/usr/src/rsbackup/src'
make  check-TESTS
make[2]: Entering directory `/usr/src/rsbackup/src'
make[3]: Entering directory `/usr/src/rsbackup/src'
PASS: test-date
PASS: test-io
PASS: test-directory
PASS: test-subprocess
PASS: test-unicode
PASS: test-timespec
PASS: test-command
PASS: test-select
PASS: test-confbase
PASS: test-check
PASS: test-device
PASS: test-host
PASS: test-volume
PASS: test-progress
PASS: test-database
PASS: test-tolines
PASS: test-globfiles
PASS: test-lock
PASS: test-split
PASS: test-parseinteger
PASS: test-prunedecay
PASS: test-eventloop
PASS: test-color
PASS: test-base64
PASS: test-indent
PASS: test-action
PASS: test-parsetimeinterval
PASS: test-namelt
SKIP: check-source
make[4]: Entering directory `/usr/src/rsbackup/src'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/usr/src/rsbackup/src'
============================================================================
Testsuite summary for rsbackup 7.0
============================================================================
# TOTAL: 29
# PASS:  28
# SKIP:  1
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory `/usr/src/rsbackup/src'
make[2]: Leaving directory `/usr/src/rsbackup/src'
make[1]: Leaving directory `/usr/src/rsbackup/src'
Making check in tests
make[1]: Entering directory `/usr/src/rsbackup/tests'
make  check-TESTS
make[2]: Entering directory `/usr/src/rsbackup/tests'
make[3]: Entering directory `/usr/src/rsbackup/tests'
SKIP: bashisms
FAIL: backup
FAIL: prune
FAIL: pruneage
FAIL: prunenever
FAIL: pruneexec
FAIL: prunedecay
FAIL: retire-device
FAIL: retire-volume
FAIL: retire-forget
FAIL: store
FAIL: check-file
PASS: check-configs
PASS: check-bad-configs
FAIL: check-mounted
FAIL: glob-store
FAIL: style
PASS: upgrade
FAIL: issue37
FAIL: partial
FAIL: issue43
FAIL: issue55
FAIL: issue70
FAIL: issue71
FAIL: prune-timeout
FAIL: concurrency
FAIL: hostgroup
FAIL: backupdaily
FAIL: backupalways
FAIL: backupinterval
make[4]: Entering directory `/usr/src/rsbackup/tests'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/usr/src/rsbackup/tests'
============================================================================
Testsuite summary for rsbackup 7.0
============================================================================
# TOTAL: 30
# PASS:  3
# SKIP:  1
# XFAIL: 0
# FAIL:  26
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to rjk@greenend.org.uk
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/usr/src/rsbackup/tests'
make[2]: *** [check-TESTS] Error 2 
make[2]: Leaving directory `/usr/src/rsbackup/tests'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/usr/src/rsbackup/tests'
make: *** [check-recursive] Error 1

[test-suite.log](https://github.com/ewxrjk/rsbackup/files/5542047/test-suite.log)

PS
Thank You for Your job.

**Comment by ewxrjk** [comment]
What does tests/test-suite.log say?

**Comment by rahu-tree** [comment]
> What does tests/test-suite.log say?

I attached to issue this file. (https://github.com/ewxrjk/rsbackup/files/5542047/test-suite.log)

**Comment by ewxrjk** [comment]
Thankyou.

```
ERROR: std::regex_constants::error_brack
```

Either something wrong in one of my regexes, or a misparse by the implementation.

**Comment by ewxrjk** [comment]
I can't reproduce this in the 7.9.2009 container (see https://hub.docker.com/_/centos). Is there anything more you can tell me about the build environment?

**Comment by rahu-tree** [comment]
> I can't reproduce this in the 7.9.2009 container (see https://hub.docker.com/_/centos). Is there anything more you can tell me about the build environment?

Hm, environment...

boost-devel-1.53.0-28.el7.x86_64
libsqlite3x-devel-20071018-20.el7.x86_64
pangomm-devel-2.40.1-1.el7.x86_64
cairomm-devel-1.12.0-1.el7.x86_64

 make -v
GNU Make 3.82

 gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

**Comment by ewxrjk** [comment]
It's the g++ version that matters, not gcc.

At any rate, that gcc version is ancient, superseded 5Y ago. I recommend using a configuration based on the dockerfile and build script  at https://github.com/ewxrjk/rsbackup/tree/master/docker/rsbcentos7, which works for me.
