### ISSUE TITLE
rsbackup has difficulty backing up files which are heavily hard-linked

### ISSUE THREAD

**Issue by pm215** [ewxrjk/rsbackup#85]
Disclaimer: I'm still using rsbackup 5.1 (the Debian package).

I have a file on my file system which has 477 links (it looks like it is the result of flatpak liking to use some sort of 'repo' structure to de-duplicate files):

```
mnementh$ stat /var/lib/flatpak/repo/objects/1f/a36c20dddf3f30b9947b6d9b0569f702dcc0a8edb354fda9a1087df67d4061.file 
  File: /var/lib/flatpak/repo/objects/1f/a36c20dddf3f30b9947b6d9b0569f702dcc0a8edb354fda9a1087df67d4061.file
  Size: 23              Blocks: 8          IO Block: 4096   regular file
Device: fe00h/65024d    Inode: 28887142    Links: 477
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-18 16:44:45.282012664 +0100
Modify: 1970-01-01 01:00:00.000000000 +0100
Change: 2020-04-15 21:24:14.325731557 +0100
 Birth: -
```

My currently-active rsbackup disk has 137 backups in it. 137 * 477 is just less than 65535, and 138 * 477 is just greater than 65535. rsbackup fails trying to create the 138th backup:

```
/etc/cron.daily/rsbackup:
WARNING: backup of mnementh:root to backup2: rsync: exited with status 13
rsync: link "/mnt/backup2/mnementh/root/2020-11-15/var/lib/flatpak/runtime/org.kde.Platform.Locale/x86_64/5.13/27
2111290342237fa5d5e1655de7a916ab68bd98a4b02299e762adfcffc7ac34/files/he/share/he/LC_MESSAGES/kauth5_qt.qm" => var
/lib/flatpak/repo/objects/1f/a36c20dddf3f30b9947b6d9b0569f702dcc0a8edb354fda9a1087df67d4061.file failed: Too many
 links (31)
Hlink node data for 2470361 already has path=var/lib/flatpak/repo/objects/1f/a36c20dddf3f30b9947b6d9b0569f702dcc0
a8edb354fda9a1087df67d4061.file (var/lib/flatpak/runtime/org.kde.Platform.Locale/x86_64/5.13/272111290342237fa5d5
e1655de7a916ab68bd98a4b02299e762adfcffc7ac34/files/he/share/he/LC_MESSAGES/kauth5_qt.qm)
rsync error: errors with program diagnostics (code 13) at hlink.c(543) [generator=3.1.3]
rsync error: received SIGUSR1 (code 19) at main.c(1458) [receiver=3.1.3]
```

Since rsbackup is only trying to hardlink files to save backup disk space, it would be nice if it handled the "oops, I can't actually create another hardlink to this file" situation by falling back to "just copy it". Perhaps this would require changes to rsync, but I thought I'd report the bug anyway.

**Comment by ewxrjk** [comment]
AFAICS this needs support from rsync.

**Comment by senji-rsbackup** [comment]
https://lists.samba.org/archive/rsync/2012-June/027671.html appears to be the most relevant comment from the rsync mailing list.

**Comment by ewxrjk** [comment]
I don't think much can be done outside rsync. And it's not trivial for rsync, for reasons expressed in that email. Perhaps a kernel fix is the answer (to support link counts bigger than 16 bits). At any rate unless anyone has any bright ideas I don't think this can possibly be fixed in rsbackup, so I'm closing it for the time being.
